// Fixture pairs, one per rule: `bad` text MUST raise the rule; `good` text MUST NOT.
// This is the regression net for false positives — the thing that lets the rule set grow.

export const CASES = [
  // ---- Family A: AI-slop tells ----
  { rule: 'overused-word',
    bad: 'We delve into the intricate tapestry of the design.',
    good: 'We look closely at the design.' },
  { rule: 'marketing-buzzword',
    bad: 'Our platform will streamline and empower your team.',
    good: 'Our platform helps your team move faster.' },
  { rule: 'cliche-opener',
    bad: "In today's fast-paced world, deadlines slip.",
    good: 'Deadlines slip when scope grows.' },
  { rule: 'filler-phrase',
    bad: "It's important to note that the build is slow.",
    good: 'The build is slow.' },
  { rule: 'manufactured-contrast',
    bad: "It's not just a linter, it's a design system.",
    good: 'It is a linter with a style system.' },
  { rule: 'conclusion-restate',
    bad: 'In conclusion, the approach works well.',
    good: 'The approach works well in our tests.' },
  { rule: 'vague-attribution',
    bad: 'Studies show that short sentences read faster.',
    good: 'Our 2024 reading test found short sentences read faster.' },
  { rule: 'despite-challenges-closer',
    bad: 'Despite these challenges, the project continues to thrive.',
    good: 'The project shipped on time.' },
  { rule: 'significance-boilerplate',
    bad: 'It stands as a testament to careful engineering.',
    good: 'It was engineered carefully.' },
  { rule: 'em-dash-overuse',
    bad: 'A — b — c — d — e.',
    good: 'A, b, c, and d.' },
  { rule: 'emoji-decoration',
    bad: '🚀 Launch the app fast.',
    good: 'Launch the app fast.' },
  { rule: 'bold-lead-in-list',
    bad: '- **Fast**: it is quick.\n- **Robust**: it is stable.\n- **Clean**: it is tidy.',
    good: '- It is quick.\n- It is stable.\n- It is tidy.' },
  { rule: 'assistant-meta',
    bad: 'I hope this helps! Let me know if you need anything.',
    good: 'See the install guide for details.' },
  { rule: 'sycophancy',
    bad: "Great question! Here is the answer.",
    good: 'Here is the answer.' },
  { rule: 'smart-quotes',
    bad: '“one” ‘two’ “three” quotes.',
    good: '"one" \'two\' "three" quotes.' },
  { rule: 'unicode-artifact',
    bad: 'A line with a nbsp artifact in it.',
    good: 'A line with a normal space in it.' },
  { rule: 'hedge-overuse',
    bad: 'Arguably, to some extent, it tends to work in many ways.',
    good: 'It works.' },

  // ---- Family B: clarity & concision ----
  { rule: 'passive-voice',
    bad: 'The cake was eaten by the dog.',
    good: 'The dog ate the cake.' },
  { rule: 'long-sentence',
    bad: 'This sentence keeps going well past any reasonable ceiling because it stacks clause upon clause and refuses to stop adding more words until it has clearly crossed thirty words total here now.',
    good: 'This sentence is short.' },
  { rule: 'wordy-phrase',
    bad: 'We restarted the server in order to apply the change.',
    good: 'We restarted the server to apply the change.' },
  { rule: 'complex-word',
    bad: 'We utilize the cache to speed things up.',
    good: 'We use the cache to speed things up.' },
  { rule: 'nominalization',
    bad: 'The team will make a decision tomorrow.',
    good: 'The team will decide tomorrow.' },
  { rule: 'weasel-word',
    bad: 'It is very really quite simple to set up.',
    good: 'It is simple to set up.' },
  { rule: 'redundant-pair',
    bad: 'We test each and every release.',
    good: 'We test every release.' },
  { rule: 'repeated-word',
    bad: 'The the build failed.',
    good: 'The build failed.' },
  { rule: 'there-is-expletive',
    bad: 'There are several bugs that block the release.',
    good: 'Several bugs block the release.' },

  // ---- Family C: style (Microsoft) ----
  { rule: 'sentence-case-heading',
    bad: '# A Comprehensive Overview Of The System',
    good: '# A comprehensive overview of the system' },
  { rule: 'heading-end-punctuation',
    bad: '# Getting started.',
    good: '# Getting started' },
  { rule: 'word-swap',
    bad: 'We leverage the e-mail pipeline.',
    good: 'We use the email pipeline.' },

  // ---- Family D: inclusive & accessible ----
  { rule: 'gendered-language',
    bad: 'The chairman briefed the manpower.',
    good: 'The chair briefed the workforce.' },
  { rule: 'ableist-language',
    bad: "That rollout was crazy and the API is lame.",
    good: 'That rollout was chaotic and the API is weak.' },
  { rule: 'vague-link-text',
    bad: 'Read the guide by clicking [here](https://example.com).',
    good: 'Read the [installation guide](https://example.com).' },
  { rule: 'skipped-heading',
    bad: '# Title\n\n### Subsection without a level two',
    good: '# Title\n\n## Section' },

  // ===== Family A extras =====
  { rule: 'negative-parallelism',
    bad: 'We ship fast, not slow. We optimize, not guess.',
    good: 'We ship fast and optimize carefully.' },
  { rule: 'tricolon-overuse',
    bad: 'We test apples, oranges, and pears. We love red, white, and blue.',
    good: 'We test apples and pears.' },
  { rule: 'serves-as-copula',
    bad: 'It serves as a guide and serves as a map for the team.',
    good: 'It is a guide for the team.' },
  { rule: 'media-coverage-boilerplate',
    bad: 'The founder was featured in major magazines and other prominent outlets.',
    good: 'The founder gave one interview in 2024.' },
  { rule: 'future-outlook-speculation',
    bad: 'The future of search lies in an evolving landscape of change.',
    good: 'Search will add three filters next quarter.' },
  { rule: 'conversational-scaffolding',
    bad: "Let's break this down: to put it simply, here's the thing.",
    good: 'The cache stores recent results.' },
  { rule: 'superficial-ing-participle',
    bad: 'It shipped, highlighting our speed, underscoring our focus.',
    good: 'It shipped on Tuesday.' },
  { rule: 'transition-scaffolding',
    bad: 'Additionally, we grew.\n\nMoreover, we shipped.\n\nFurthermore, we hired.',
    good: 'We grew. We shipped. We hired.' },
  { rule: 'interrogative-answer',
    bad: 'The result? Devastating. Our reaction? Immediate.',
    good: 'The result was a slower build.' },
  { rule: 'excessive-bold',
    bad: '**One** **two** **three** **four** words here now.',
    good: 'One two three four words here now.' },
  { rule: 'listicle-reflex',
    bad: '- fast\n- clean\n- small\n- neat\n- tidy\n- quick',
    good: 'The system is fast and small, with a clean, tidy layout overall.' },
  { rule: 'uniform-cadence',
    bad: 'The cat ran fast today. The dog sat down here. The bird flew up high. The fish swam down deep. The fox jumped over there. The owl slept all day.',
    good: 'Yes. The afternoon planning meeting ran far too long because nobody could agree on the release date. No. It shipped. After three weeks of careful and heated debate the whole team finally converged on one plan. Done.' },

  // ===== Family B extras =====
  { rule: 'adverb-overuse',
    bad: 'He quickly, slowly, quietly, loudly, and badly ran the test.',
    good: 'He ran the test.' },
  { rule: 'undefined-acronym',
    bad: 'The ZQP pipeline failed during the ZQP run.',
    good: 'The Zonal Queue Processor (ZQP) failed during the ZQP run.' },
  { rule: 'reading-grade', pack: 'plain',
    bad: 'The aforementioned implementation necessitates substantial computational infrastructure because the underlying algorithmic methodology demonstrates considerable inefficiency whenever processing voluminous heterogeneous datasets under simultaneous concurrent operational conditions that consistently exceed the recommended capacity thresholds established previously.',
    good: 'We use short words. We write clearly. Read it now.' },

  // ===== Family C shared =====
  { rule: 'serial-comma',
    bad: 'We support apples, oranges and pears.',
    good: 'We support apples, oranges, and pears.' },
  { rule: 'use-contractions',
    bad: 'We do not ship on Fridays.',
    good: "We don't ship on Fridays." },
  { rule: 'second-person',
    bad: 'The user should click Save to continue.',
    good: 'Click Save to continue.' },
  { rule: 'present-tense',
    bad: 'You will see a confirmation dialog.',
    good: 'You see a confirmation dialog.' },
  { rule: 'singular-they',
    bad: 'Each developer submits his or her code.',
    good: 'Each developer submits their code.' },
  { rule: 'no-please-instructions',
    bad: 'Please run the build script first.',
    good: 'Run the build script first.' },
  { rule: 'terminology-consistency',
    bad: 'Sign in on the home page. Later, log in from the app.',
    good: 'Sign in on the home page. Later, sign in from the app.' },

  // ===== Family C: Microsoft pack (default) =====
  { rule: 'no-space-em-dash',
    bad: 'The build — slow as it is — passed.',
    good: 'The build—slow as it is—passed.' },
  { rule: 'no-internal-caps',
    bad: 'We store it in fooBar for now.',
    good: 'We store it in foobar for now.' },
  { rule: 'omit-you-can',
    bad: 'You can click Save to keep changes.',
    good: 'Click Save to keep changes.' },
  { rule: 'avoid-we',
    bad: 'We build it. We ship it. We grow our product.',
    good: 'The product ships weekly.' },
  { rule: 'spell-out-small-numbers',
    bad: 'There are 3 ways to do this.',
    good: 'There are three ways to do this.' },
  { rule: 'no-numeral-sentence-start',
    bad: '3 ways exist to solve this.',
    good: 'Three ways exist to solve this.' },
  { rule: 'large-number-grouping',
    bad: 'It processed 100000 rows.',
    good: 'It processed 100,000 rows.' },
  { rule: 'no-k-m-b',
    bad: 'The round was $30M in total.',
    good: 'The round was 30 million dollars in total.' },
  { rule: 'leading-zero',
    bad: 'Pour .5 liters of water.',
    good: 'Pour 0.5 liters of water.' },

  // ===== Family C: Google pack =====
  { rule: 'no-gerund-heading', pack: 'google',
    bad: '# Installing the application',
    good: '# Install the application' },
  { rule: 'no-link-in-heading', pack: 'google',
    bad: '# See the [reference docs](https://example.com)',
    good: '# See the reference docs' },
  { rule: 'latinism-abbreviation', pack: 'google',
    bad: 'Use a text tool, e.g. grep.',
    good: 'Use a text tool, for example grep.' },
  { rule: 'minimizing-words', pack: 'google',
    bad: 'Just run it — setup is easy.',
    good: 'Run the setup script.' },
  { rule: 'no-abbreviation-as-verb', pack: 'google',
    bad: 'First, ssh into the server.',
    good: 'First, use SSH to reach the server.' },
  { rule: 'no-periods-in-acronyms', pack: 'google',
    bad: 'The U.S. region is default.',
    good: 'The US region is default.' },
  { rule: 'no-exclamation', pack: 'google',
    bad: 'The deploy succeeded!',
    good: 'The deploy succeeded.' },
  { rule: 'american-spelling', pack: 'google',
    bad: 'Pick a accent colour for the theme.',
    good: 'Pick an accent color for the theme.' },
  { rule: 'no-preannounce', pack: 'google',
    bad: 'This API is currently supported.',
    good: 'This API is supported.' },
  { rule: 'no-directional', pack: 'google',
    bad: 'See the configuration section above.',
    good: 'See the configuration section in Setup.' },

  // ===== Hype + terminology casing =====
  { rule: 'hype-intensifier',
    bad: 'This greatly simplifies the workflow.',
    good: 'This removes two manual steps from the workflow.' },
  { rule: 'acronym-case',
    bad: 'Run the DDL, then edit the ddl file by hand.',
    good: 'Run the DDL, then edit the DDL file by hand.' },
  { rule: 'acronym-plural',
    bad: "Register your UDF's in the catalog.",
    good: 'Register your UDFs in the catalog.' },
  { rule: 'inconsistent-capitalization',
    bad: 'The Catalog Store holds the entries; update the catalog store after a change.',
    good: 'The catalog store holds the entries; update the catalog store after a change.' },
  { rule: 'second-person',
    bad: 'Users can configure the endpoint.',
    good: 'You can configure the endpoint.' },

  // ===== Markdown structure / quality =====
  { rule: 'emphasis-as-heading',
    bad: '**Configuration**\n\nSet the timeout value.',
    good: '## Configuration\n\nSet the timeout value.' },
  { rule: 'bare-url',
    bad: 'See https://example.com/guide for the full guide.',
    good: 'See [the full guide](https://example.com/guide) for details.' },
  { rule: 'fenced-code-language',
    bad: '```\nnpm install\n```',
    good: '```bash\nnpm install\n```' },
  { rule: 'duplicate-heading',
    bad: '# Setup\n\nFirst steps.\n\n# Setup\n\nMore steps.',
    good: '# Setup\n\nFirst steps.\n\n# Teardown\n\nCleanup steps.' },

  // ===== Family C: AP / Chicago / plain packs =====
  { rule: 'ap-serial-comma', pack: 'ap',
    bad: 'We shipped docs, tests, and code.',
    good: 'We shipped docs, tests and code.' },
  { rule: 'ap-number-style', pack: 'ap',
    bad: 'The release closed 9 issues.',
    good: 'The release closed nine issues.' },
  { rule: 'chicago-number-style', pack: 'chicago',
    bad: 'The working group has 42 members.',
    good: 'The working group has forty-two members.' },
  { rule: 'plain-long-sentence', pack: 'plain',
    bad: 'This particular sentence has been written so that it clearly contains a few more than twenty distinct words in total here today.',
    good: 'It is short.' },

  // ===== Family D extras =====
  { rule: 'person-first-language',
    bad: 'He suffers from a chronic condition.',
    good: 'He has a chronic condition.' },
  { rule: 'gendered-address',
    bad: 'Hey guys, ship it today.',
    good: 'Hey everyone, ship it today.' },
  { rule: 'tech-historical-terms',
    bad: 'Add the host to the whitelist.',
    good: 'Add the host to the allowlist.' },
  { rule: 'violent-tech-metaphor',
    bad: 'Abort the request when it stalls.',
    good: 'Stop the request when it stalls.' },
  { rule: 'ageist-classist-cultural',
    bad: 'It runs on a third-world budget.',
    good: 'It runs on a small budget.' },
  { rule: 'missing-alt-text',
    bad: 'Here is the diagram: ![](architecture.png)',
    good: 'Here is the diagram: ![system architecture](architecture.png)' },
  { rule: 'all-caps-shouting',
    bad: 'THIS IS REALLY VERY URGENT NOW.',
    good: 'This is urgent.' },

  // ===== Family E extras =====
  { rule: 'markup-leak',
    bad: '##Heading with no space',
    good: '## Heading with a space' },
  { rule: 'thematic-break-before-heading',
    bad: 'Intro paragraph here.\n\n---\n## Next section',
    good: 'Intro paragraph here.\n\n## Next section' },
  { rule: 'bullet-overuse',
    bad: '- a\n- b\n- c\n- d\n- e\n- f\n- g\n- h\n- i',
    good: 'The list is short and mostly prose with a sentence here.' },
  { rule: 'double-space',
    bad: 'This sentence has  a double space.',
    good: 'This sentence has a single space.' },
  { rule: 'redundant-acronym',
    bad: 'Enter your PIN number to continue.',
    good: 'Enter your PIN to continue.' },
  { rule: 'indefinite-article',
    bad: 'It is a apple on the table.',
    good: 'It is an apple on the table.' },

  // ===== Family F: citations =====
  { rule: 'placeholder-citation',
    bad: 'This claim is supported [citation needed].',
    good: 'This claim is supported by our 2024 study.' },
  { rule: 'tracking-param-in-citation',
    bad: 'Source: https://example.com/post?utm_source=newsletter for details.',
    good: 'Source: https://example.com/post for details.' },
  { rule: 'malformed-doi-isbn',
    bad: 'See doi: 12.345/not-a-real-doi for the paper.',
    good: 'See doi: 10.1000/xyz123 for the paper.' },
  { rule: 'unused-named-ref',
    bad: 'Some plain paragraph text here.\n\n[ref]: https://example.com',
    good: 'Some [linked text][ref] here.\n\n[ref]: https://example.com' },

  // ---- Vale-parity pack (Microsoft/Google/AP/Chicago/Plain) ----
  { rule: "microsoft-ampm", pack: "microsoft",
    bad: "The webinar starts at 3PM and the recording posts by 9 pm.",
    good: "The webinar starts at 3 PM and the recording posts by 9 PM." },
  { rule: "microsoft-accessibility", pack: "microsoft",
    bad: "He is a victim of stroke and suffers from chronic pain.",
    good: "He had a stroke and lives with chronic pain." },
  { rule: "microsoft-adverbs", pack: "microsoft",
    bad: "He quickly and carefully reviewed the report.",
    good: "He reviewed the report." },
  { rule: "microsoft-auto-hyphenation", pack: "microsoft",
    bad: "The auto-correct feature is enabled by default.",
    good: "The autocorrect feature is enabled by default." },
  { rule: "microsoft-avoid-words", pack: "microsoft",
    bad: "The backend service handles all incoming requests.",
    good: "The server handles all incoming requests." },
  { rule: "microsoft-contractions", pack: "microsoft",
    bad: "It is ready and we are shipping it now.",
    good: "It's ready and we're shipping it now." },
  { rule: "ms-date-format", pack: "microsoft",
    bad: "The feature was released on 31 July 2016 to all users.",
    good: "The feature was released on July 31, 2016 to all users." },
  { rule: "ms-date-numbers", pack: "microsoft",
    bad: "The release is scheduled for July first this year.",
    good: "The release is scheduled for July 1 this year." },
  { rule: "ms-date-order", pack: "microsoft",
    bad: "Set the expiration date to 12/25/2024 in the form.",
    good: "Set the expiration date to December 25, 2024 in the form." },
  { rule: "ms-ellipses", pack: "microsoft",
    bad: "Wait for the build to finish... then deploy.",
    good: "Wait for the build to finish, then deploy." },
  { rule: "ms-first-person", pack: "microsoft",
    bad: "I think I'll update my own profile settings.",
    good: "The team updates the profile settings for everyone." },
  { rule: "ms-foreign-abbrev", pack: "microsoft",
    bad: "Pick a database, eg PostgreSQL, for storage.",
    good: "Pick a database such as PostgreSQL for storage." },
  { rule: "ms-gender-slash", pack: "microsoft",
    bad: "Ask he/she to sign in before continuing.",
    good: "Ask the user to sign in before continuing." },
  { rule: "ms-gender-bias", pack: "microsoft",
    bad: "We need more manpower to staff the launch.",
    good: "We need more staff to run the launch." },
  { rule: "microsoft-general-url", pack: "microsoft",
    bad: "Enter the URL in the box and press Go.",
    good: "Enter the web address in the box and press Go." },
  { rule: "microsoft-heading-acronyms", pack: "microsoft",
    bad: "## Configure the API endpoint\n\nSome body text.",
    good: "## Configure the service endpoint\n\nSome body text." },
  { rule: "microsoft-heading-colons", pack: "microsoft",
    bad: "## Setup: getting started\n\nBody.",
    good: "## Setup: Getting started\n\nBody." },
  { rule: "ms-adverb-hyphen", pack: "microsoft",
    bad: "The newly-created file is ready to use.",
    good: "The newly created file is ready to use." },
  { rule: "ms-negative-number-endash", pack: "microsoft",
    bad: "The temperature dropped to -5 degrees overnight.",
    good: "The temperature dropped to –5 degrees overnight." },
  { rule: "ms-ordinal-ly", pack: "microsoft",
    bad: "Firstly, install the package and restart.",
    good: "First, install the package and restart." },
  { rule: "ms-percentages", pack: "microsoft",
    bad: "About fifty percent of users upgraded.",
    good: "About 50 percent of users upgraded." },
  { rule: "ms-plurals-parenthetical", pack: "microsoft",
    bad: "Select the file(s) you want to upload.",
    good: "Select the files you want to upload." },
  { rule: "microsoft-quotes-punctuation", pack: "microsoft",
    bad: "The dialog shows the word “Save”, then closes.",
    good: "The dialog shows the word “Save,” then closes." },
  { rule: "microsoft-range-time", pack: "microsoft",
    bad: "The support desk is open 9 AM - 5 PM on weekdays.",
    good: "The support desk is open 9 AM to 5 PM on weekdays." },
  { rule: "microsoft-semicolon", pack: "microsoft",
    bad: "I finished the report; she reviewed it later that day.",
    good: "I finished the report. She reviewed it later that day." },
  { rule: "ms-suspended-hyphen", pack: "microsoft",
    bad: "Run the pre- and post-deployment checks before release.",
    good: "Run the predeployment and postdeployment checks before release." },
  { rule: "ms-term-swaps", pack: "microsoft",
    bad: "Install the anti-virus software before you reboot the smart phone.",
    good: "Install the antivirus software before you reboot the phone." },
  { rule: "ms-url-of", pack: "microsoft",
    bad: "Copy the URL for the resource into the form.",
    good: "Copy the URL of the resource into the form." },
  { rule: "ms-units-spelled-number", pack: "microsoft",
    bad: "The charging cable is ten meters long and weighs five pounds.",
    good: "The charging cable is 10 meters long and weighs 5 pounds." },
  { rule: "ms-vocab-az-wordlist", pack: "microsoft",
    bad: "He will author the sample and alert the alias above.",
    good: "The team shipped the new dashboard to every customer today." },
  { rule: "ms-wordiness", pack: "microsoft",
    bad: "You should utilize the system in order to fix it due to the fact that it works.",
    good: "You should use the system to fix it because it works." },
  { rule: "google-ampm", pack: "google",
    bad: "Let's sync up at 3pm before the standup.",
    good: "Let's sync up at 3 PM before the standup." },
  { rule: "google-contractions", pack: "google",
    bad: "It is ready and we are shipping it now.",
    good: "It's ready and we're shipping it now." },
  { rule: "google-date-format", pack: "google",
    bad: "The release shipped on 31 July 2016 to all users.",
    good: "The release shipped on July 31, 2016 to all users." },
  { rule: "google-ellipses", pack: "google",
    bad: "Well... it depends on your configuration.",
    good: "Well, it depends on your configuration." },
  { rule: "google-dash-spacing", pack: "google",
    bad: "The update improves speed — and reliability — across the board.",
    good: "The update improves speed—and reliability—across the board." },
  { rule: "google-first-person", pack: "google",
    bad: "I think we should test this, and let me check my notes first.",
    good: "Run the test, then check the notes first." },
  { rule: "google-gender-neutral-pronoun", pack: "google",
    bad: "Each user can update he/she profile from the settings page.",
    good: "Each user can update their profile from the settings page." },
  { rule: "google-gender-bias", pack: "google",
    bad: "A fireman and a policeman arrived to inspect the manmade structure.",
    good: "A firefighter and a police officer arrived to inspect the manufactured structure." },
  { rule: "google-ly-hyphen", pack: "google",
    bad: "Use a newly-created token for each request.",
    good: "Use a newly created token for each request." },
  { rule: "google-optional-plurals", pack: "google",
    bad: "Upload the file(s) you want to share.",
    good: "Upload the files you want to share." },
  { rule: "google-ordinal", pack: "google",
    bad: "Press the 1st button, then the 2nd one.",
    good: "Press the first button, then the second one." },
  { rule: "google-quote-punctuation", pack: "google",
    bad: "She told me to read the \"manual\".",
    good: "She told me to read the \"manual.\"" },
  { rule: "google-number-range-words", pack: "google",
    bad: "The build takes from 10-20 minutes.",
    good: "The build takes 10-20 minutes." },
  { rule: "google-semicolons", pack: "google",
    bad: "I came to the office; I saw the problem.",
    good: "I came to the office and I saw the problem." },
  { rule: "google-slang", pack: "google",
    bad: "TL;DR: just ship the defaults, IMO.",
    good: "In summary, ship the defaults; in my opinion that is best." },
  { rule: "google-units-nbsp", pack: "google",
    bad: "The file is 10MB and loads in 200ms.",
    good: "The file is 10 MB and loads in 200 ms." },
  { rule: "avoid-first-person-plural", pack: "google",
    bad: "We recommend backups, and we test them weekly.",
    good: "Back up your data and test it weekly." },
  { rule: "avoid-will-future-tense", pack: "google",
    bad: "The installer will download files and will then restart.",
    good: "The installer downloads files and then restarts." },
  { rule: "google-word-list", pack: "google",
    bad: "Send me an e-mail in order to confirm the change.",
    good: "Send me an email to confirm the change." },
  { rule: "ap-percent", pack: "ap",
    bad: "Adoption rose 20% last quarter.",
    good: "Adoption rose 20 percent last quarter." },
  { rule: "ap-time-format", pack: "ap",
    bad: "The release ships at 10 AM.",
    good: "The release ships at 10 a.m." },
  { rule: "ap-dollar-style", pack: "ap",
    bad: "The acquisition cost 5 million dollars.",
    good: "The acquisition cost $5 million." },
  { rule: "ap-over-quantity", pack: "ap",
    bad: "The repository has over 500 commits.",
    good: "The repository has more than 500 commits." },
  { rule: "ap-toward", pack: "ap",
    bad: "We are migrating towards the new API.",
    good: "We are migrating toward the new API." },
  { rule: "ap-ampersand", pack: "ap",
    bad: "Install the parser & the linter before running tests.",
    good: "Install the parser and the linter before running tests." },
  { rule: "chicago-directional-s", pack: "chicago",
    bad: "We steadily moved towards the goal.",
    good: "We steadily moved toward the goal." },
  { rule: "chicago-percent-symbol", pack: "chicago",
    bad: "About 40% of the users opted in.",
    good: "About 40 percent of the users opted in." },
  { rule: "chicago-em-dash-spacing", pack: "chicago",
    bad: "The result — a clean build — surprised everyone.",
    good: "The result—a clean build—surprised everyone." },
  { rule: "chicago-ellipsis", pack: "chicago",
    bad: "Then… nothing happened.",
    good: "Then . . . nothing happened." },
  { rule: "chicago-united-states-noun", pack: "chicago",
    bad: "The US is investing heavily in the program.",
    good: "The US economy is strong this year." },
  { rule: "chicago-ibid", pack: "chicago",
    bad: "See ibid. for the full derivation.",
    good: "See the earlier note for the full derivation." },
  { rule: "plain-hidden-verb", pack: "plain",
    bad: "The reviewer will make a recommendation by Friday.",
    good: "The reviewer will recommend a fix by Friday." },
  { rule: "plain-shall", pack: "plain",
    bad: "The applicant shall submit the completed form.",
    good: "The applicant must submit the completed form." },
  { rule: "plain-required-to", pack: "plain",
    bad: "Users are required to verify their email address.",
    good: "Users must verify their email address." },
  { rule: "plain-legalese-phrase", pack: "plain",
    bad: "Complete all checks prior to deployment, pursuant to the policy.",
    good: "Complete all checks before deployment, under the policy." },
  { rule: "plain-legalese-word", pack: "plain",
    bad: "All obligations described herein remain binding notwithstanding any change.",
    good: "All obligations in this contract remain binding despite any change." },
  { rule: "plain-double-negative", pack: "plain",
    bad: "This failure mode is not uncommon in production.",
    good: "This failure mode is common in production." },
];
